remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "dirt"

locale: "sk-SK"
title: "Digitálny školník"
title_separator: "-"
subtitle: "O školách, vzdelávaní, AI a edtechу"
name: "Roman Baranovic"
description: "Píšem o školách, vzdelávaní, AI vo vzdelávaní, edtechu a digitálnom svete."
url: "https://romanbaranovic.github.io"
og_image: "/assets/images/avatar.jpg"
baseurl: ""
repository: "romanbaranovic/romanbaranovic.github.io"

breadcrumbs: true

search: true
search_full_content: true

markdown: kramdown
permalink: /:year/:month/:day/:title/

author:
  name: "Roman Baranovic"
  avatar: "/assets/images/avatar.jpg"
  bio: "Som digitálny školník. Píšem o školách, vzdelávaní, AI vo vzdelávaní, edtechu a digitálnom svete."
  location: "Slovensko"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/romanbaranovic/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/rombaran/"
    - label: "Bluesky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/rombaran.bsky.social"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@rombaran"

comments:
  provider: "giscus"
  giscus:
    repo_id: "R_kgDORo29pg"
    category_name: "General"
    category_id: "DIC_kwDORo29ps4C44sg"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-M37R8EG602"
    anonymize_ip: true

paginate: 8
paginate_path: /page:num/

timezone: Europe/Bratislava

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
