title: Digitálny školník
description: Osobný blog
url: "https://romanbaranovic.github.io"
remote_theme: kitian616/jekyll-TeXt-theme

author:
  name: Roman Baranovic

permalink: /:year/:month/:day/:title/

markdown: kramdown

google_analytics: G-M37R8EG602

text_skin: default
highlight_theme: default

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
